#!/bin/bash

echo "Starte Systembereinigung..."
echo
sudo apt clean
sudo apt autoremove -y

echo
echo "Starte Backup..."
echo

# Definieren Sie den Pfad für das Backup-Ziel
BACKUP_DIR="$HOME/.backups"
BACKUP_DIR_EXT="/media/jens/Elements/hpbackup/"
# BACKUP_FILE="backup_$(date +%Y%m%d).tar.gz"
BACKUP_FILE="hpbackup.tar.gz"
github="$HOME/github"

# Backup-Verzeichnis erstellen, falls es nicht existiert
mkdir -p "$BACKUP_DIR"

# Erstellen des tar.gz-Archivs, inklusive versteckter Dateien und Verzeichnisse
# --exclude wird verwendet, um das Backup-Verzeichnis selbst auszuschließen und so eine Endlosschleife zu verhindern
# tar -czf "$BACKUP_DIR/$BACKUP_FILE" --exclude="$BACKUP_DIR" .
tar -czf "$BACKUP_DIR/$BACKUP_FILE" "$HOME" --exclude="$BACKUP_DIR" .

# Dateien separat in Ziel-Pfad kopieren
cp -u $HOME/.bashrc "$BACKUP_DIR" 2>/dev/null
cp -u $HOME/.bashrc "$HOME/.bashrc.bak" 2>/dev/null
cp -u $HOME/.bashrc.bak "$BACKUP_DIR" 2>/dev/null
cp -u $HOME/.vimrc "$BACKUP_DIR" 2>/dev/null
cp -u $HOME/.local/share/backgrounds/* "$BACKUP_DIR" 2>/dev/null

echo
echo "Backup erstellt in: "$BACKUP_DIR""
echo

# Dateien von lokaler auf externe Festplatte kopieren
echo "Kopiere Dateien von "$BACKUP_DIR" nach "$BACKUP_DIR_EXT"... "

cp -u $BACKUP_DIR/* $BACKUP_DIR_EXT 
cp -u $BACKUP_DIR/.bashrc $BACKUP_DIR_EXT 
cp -u $BACKUP_DIR/.bashrc.bak $BACKUP_DIR_EXT 
cp -u $BACKUP_DIR/.vimrc $BACKUP_DIR_EXT 

echo "Fertig"
echo
echo "Kopiere Dateien für GitHub..."

# Dateien für GitHub kopieren  
gitupd

echo "Fertig"
echo
