#!/bin/bash

#  _
# | |__  _   _  ___ MIT License
# | '_ \| | | |/ _ \
# | |_) | |_| |  __/
# |_.__/ \__, |\___|
#        |___/
#
# Script        : bye
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# Date          : 2024-05-20
# Description   : Shutdown system
# Requires root : No

shutdown -P now
