#!/bin/bash

#  _
# | |__  _   _  ___ MIT License
# | '_ \| | | |/ _ \
# | |_) | |_| |  __/
# |_.__/ \__, |\___|
#        |___/
#
# Script        : bye
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# E-Mail        : ochilinux84@gmail.com
# Date          : 2024-06-02
# Description   : Shutdown system
# Requires root : No

shutdown -P now
