#!/bin/bash
#      _ _                 _       _     
#   __| (_)___ _ __   __ _| |_ ___| |__  
#  / _` | / __| '_ \ / _` | __/ __| '_ \ 
# | (_| | \__ \ |_) | (_| | || (__| | | |
#  \__,_|_|___/ .__/ \__,_|\__\___|_| |_|
#             |_|                        
#
# Script        : dispatch
# Author        : Jens Ochmann
# Description   : Controls and monitors the execution of various system tasks.
# Location      : /usr/local/bin/
# Requires root : Yes
# Usage         : Used internally by startup scripts.

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Starting dispatch operations...${NC}"

# Define directories
declare -A DIRS=(
    [dot.bashrc]="$HOME/.bashrc"
    [dot.vimrc]="$HOME/.vimrc"
    [rc.conf]="$HOME/.config/ranger/rc.conf"
    [rc.lua]="$HOME/.config/awesome/rc.lua"
    [backup]="/usr/local/bin/"
    [gitupd]="/usr/local/bin/"
    [snapcrash]="/usr/local/bin/"
    [update]="/usr/local/bin/"
    [dispatch]="/usr/local/bin/"
    [startup]="/usr/local/bin/"
)

GITHUB_DIR="$HOME/github"

# Copy scripts and config files
for file in "${!DIRS[@]}"; do
    src="$GITHUB_DIR/$file"
    dest="${DIRS[$file]}"

    if [[ $dest == */bin/* ]]; then
        if sudo cp -u "$src" "$dest" && sudo chmod +x "$dest$file"; then
            echo -e "${YELLOW}Copied scripts and set executable: $file${NC}"
        else
            echo -e "${RED}Failed to copy scripts or set executable: $file${NC}"
        fi
    else
        if cp -u "$src" "$dest"; then
            echo -e "${YELLOW}Copied config files: $file${NC}"
        else
            echo -e "${RED}Failed to copy config files: $file${NC}"
        fi
    fi
done
echo -e "${YELLOW}All files have been copied successfully.${NC}"
