#!/bin/bash

GITHUB_DIR="$HOME/GITHUB_DIR"

## copy files for GITHUB_DIR

# dotfiles
cp -u $HOME/.bashrc "$GITHUB_DIR/dot.bashrc"
cp -u $HOME/.vimrc "$GITHUB_DIR/dot.vimrc"
cp -u $HOME/.config/ranger/rc.conf "$GITHUB_DIR/rc.conf"

# scripts
cp -u /usr/local/bin/* "$GITHUB_DIR/*_script"  #check functionality

# info files
cp -u $HOME/Dokumente/info/* "$GITHUB_DIR/"

# config files
cp -u $HOME/.config/bpytop/bpytop.conf "$GITHUB_DIR"
cp -u $HOME/.config/htop/htoprc "$GITHUB_DIR"
cp -u $HOME/.config/neofetch/config.conf "$GITHUB_DIR/neofetch_config.conf"

#exit
