#!/bin/bash

# Script: gitupd
# Author: Jens Ochmann
# Purpose: Backup and sync local files to GitHub directory.
# Location: /usr/local/bin
# Usage: Execute with './gitupd' to update files to $HOME/github.

GITHUB_DIR="$HOME/github"

# Check if the GitHub directory exists
if [ ! -d "$GITHUB_DIR" ]; then
    echo "GitHub directory does not exist. Creating directory: $GITHUB_DIR"
    mkdir -p "$GITHUB_DIR"
fi

echo "Updating dotfiles..."
# dotfiles
cp -u $HOME/.bashrc "$GITHUB_DIR/dot.bashrc"
cp -u $HOME/.vimrc "$GITHUB_DIR/dot.vimrc"

echo "Updating scripts..."
# scripts
# Here, you should define a list of specific scripts to be copied.
declare -a scripts=("backup" "gitupd" "snapcrash" "update" "dispatch" "startup")
for script in "${scripts[@]}"; do
    cp -u "/usr/local/bin/$script" "$GITHUB_DIR/"
done

echo "Updating info files..."
# info files
cp -u $HOME/Dokumente/info/* "$GITHUB_DIR/"

echo "Updating configuration files..."
# config files
cp -u $HOME/.config/ranger/rc.conf "$GITHUB_DIR/rc.conf"

echo "Update process completed."
