#!/bin/bash

#        _ _                   _ 
#   __ _(_) |_ _   _ _ __   __| |
#  / _` | | __| | | | '_ \ / _` |
# | (_| | | |_| |_| | |_) | (_| |
#  \__, |_|\__|\__,_| .__/ \__,_|
#  |___/            |_|  
#
# Script        : gitupd
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# Description   : Backup and sync local files to GitHub directory.
# Requires root : No

# Load config file
source $HOME/.config/sc.conf

# Function to print messages in yellow
echo_yellow() {
    echo -e "${YELLOW}$1${NC}"
}

# Check if the GitHub directory exists
if [ ! -d "$GITHUB_DIR" ]; then
    echo_yellow "GitHub directory does not exist. Creating directory: $GITHUB_DIR"
    mkdir -p "$GITHUB_DIR"
fi

echo_yellow "Updating configfiles..."

# config files
cp -u $HOME/.bashrc "$GITHUB_DIR/dot.bashrc" || echo -e "${RED}Failed to update .bashrc${NC}"
cp -u $HOME/.vimrc "$GITHUB_DIR/dot.vimrc" || echo -e "${RED}Failed to update .vimrc${NC}"
cp -u $HOME/.config/awesome/rc.lua "$GITHUB_DIR/rc.lua" || echo -e "${RED}Failed to update rc.lua${NC}"
cp -u $HOME/.config/awesome/rc.lua.original "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"

cp -u $HOME/.config/ranger/rc.conf "$GITHUB_DIR/rc.conf" || echo -e "${RED}Failed to update rc.conf${NC}"
cp -u $HOME/.config/picom/picom.conf "$GITHUB_DIR/picom.conf" || echo -e "${RED}Failed to update picom.conf${NC}"

echo_yellow "Updating scripts..."

# scripts
# Here, you should define a list of specific scripts to be copied.
declare -a scripts=("backup" "gitupd" "snapcrash" "update" "dispatch" "startup" "bye")
for script in "${scripts[@]}"; do
    cp -u "/usr/local/bin/$script" "$GITHUB_DIR/$script" || echo -e "${RED}Failed to update $script${NC}"
done

echo_yellow "Update process completed."
