#!/bin/bash

#                              _
#  _ __ ___   ___  _   _ _ __ | |_ _ __ ___   __ _ _ __ MIT Licence
# | '_ ` _ \ / _ \| | | | '_ \| __| '_ ` _ \ / _` | '_ \
# | | | | | | (_) | |_| | | | | |_| | | | | | (_| | | | |
# |_| |_| |_|\___/ \__,_|_| |_|\__|_| |_| |_|\__,_|_| |_|
# 
#
# Script        : mountman
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# Date          : 2024-05-20
# Description   : Mount/Unmount external devices.
# Requires root : Yes
# Define colors

# Load config file
CONFIG_FILE="$HOME/.config/sc.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "${RED}Error: Configuration file not found.${NC}"
    echo -e "${RED}Please ensure the configuration file 'sc.con' exists at $HOME/.config/${NC}"
    exit 1
fi

# Default mount path
MOUNT_BASE="/media/$USER"

## Function to clear the screen
#clear_screen() {
#    clear
#}

# Function to display the header
display_header() {
    clear_screen
    echo -e ""
    echo -e "${BLUE}Mountman - mount/unmount external devices${NC}"
    echo -e ""
}

# Function to mount a device
mount_device() {
    local device=$1
    local mount_point=$2

    if [[ ! -d $mount_point ]]; then
        sudo mkdir -p "$mount_point"
    fi

    sudo mount "$device" "$mount_point"
    if [[ $? -eq 0 ]]; then
        echo ""
        echo -e "${GREEN}The device $device has been successfully mounted to $mount_point.${NC}"
    else
        echo ""
        echo -e "${RED}Failed to mount $device.${NC}"
    fi
}

# Function to unmount a device
unmount_device() {
    local device=$1
    sudo umount "$device"
    if [[ $? -eq 0 ]]; then
        echo -e ""
        echo -e "${GREEN}The device $device has been successfully unmounted.${NC}"
    else
        echo -e "${RED}Failed to unmount $device.${NC}"
    fi
}

# List available external devices
list_devices() {
    lsblk -o NAME,MODEL,SIZE,TYPE,MOUNTPOINT | grep -E "disk|part" | grep -vE "loop|sr0|nvme0n1"
}

# Main menu
main_menu() {
    display_header
    echo -e "${YELLOW}Available external devices:${NC}"
    devices=$(list_devices)
    
    if [[ -z "$devices" ]]; then
        echo -e "${RED}No external devices available. Exiting.${NC}"
        exit 1
    fi
    
    echo "$devices"
    echo ""
    echo -e "${YELLOW}Enter the device name:${NC}"
    read device_name

    if [[ -z $device_name ]]; then
        echo -e "${RED}No device selected. Exiting.${NC}"
        exit 1
    fi

    local device_path="/dev/$device_name"

    if [[ ! -b $device_path ]]; then
        echo -e "${RED}Invalid device. Exiting.${NC}"
        exit 1
    fi
    
    echo -e ""
    echo -e "${YELLOW}Select an action:${NC}"
    echo -e "${YELLOW}1: Mount${NC}"
    echo -e "${YELLOW}2: Unmount${NC}"
    read action

    case $action in
        1)
            local label=$(lsblk -no LABEL $device_path)
            if [[ -z $label ]]; then
                label=$device_name
            fi
            # Replace all non-alphanumeric characters with nothing
            label=$(echo $label | tr -cd '[:alnum:]')
            mount_point="$MOUNT_BASE/$label"

            mount_device "$device_path" "$mount_point"
            ;;
        2)
            unmount_device "$device_path"
            ;;
        *)
            echo -e "${RED}Invalid selection. Exiting.${NC}"
            exit 1
            ;;
    esac
}

# Run script
main_menu
