#!/bin/bash

#                                            _     
#  ___ _ __   __ _ _ __   ___ _ __ __ _ ___ | |__  
# / __| '_ \ / _` | '_ \ / __| '__/ _` / __|| '_ \ 
# \__ \ | | | (_| | |_) | (__| | | (_| \__ \| | | |
# |___/_| |_|\__,_| .__/ \___|_|  \__,_|___/|_| |_|
#                 |_|                             
#
# Script        : snapcrash
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# Date          : 2024-05-18
# Description   : Terminates, updates, removes, and reinstalls the Snap Store to resolve common issues.
# Requires root : Yes

# Load config file
CONFIG_FILE="$HOME/.config/sc.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "${RED}Error: Configuration file not found.${NC}"
    echo -e "${RED}Please ensure the configuration file 'sc.conf' exists at $HOME/.config/${NC}"
    exit 1
fi

echo
echo -e "${YELLOW}Deleting all Snap Store processes...${NC}"
killall snap-store

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Snap Store processes successfully terminated.${NC}"
else
    echo -e "${RED}Error terminating Snap Store processes. They may not have been active.${NC}"
fi

echo
echo -e "${YELLOW}Updating Snaps...${NC}"
sudo snap refresh

echo
echo -e "${YELLOW}Updating package lists and performing a full upgrade...${NC}"
if sudo apt update && sudo apt full-upgrade -y; then
    echo -e "${GREEN}System successfully updated.${NC}"
else
    echo -e "${RED}Error updating the system.${NC}"
fi

echo
echo -e "${YELLOW}Removing Snap Store...${NC}"
if sudo snap remove snap-store; then
    echo -e "${GREEN}Snap Store successfully removed.${NC}"
else
    echo -e "${RED}Error removing the Snap Store.${NC}"
fi

echo
echo -e "${YELLOW}Installing Snap Store...${NC}"
if sudo snap install snap-store; then
    echo -e "${GREEN}Snap Store successfully installed.${NC}"
    echo
else
    echo -e "${RED}Error installing the Snap Store.${NC}"
    echo
fi
