#!/bin/bash

#                                            _     
#  ___ _ __   __ _ _ __   ___ _ __ __ _ ___ | |__  
# / __| '_ \ / _` | '_ \ / __| '__/ _` / __|| '_ \ 
# \__ \ | | | (_| | |_) | (__| | | (_| \__ \| | | |
# |___/_| |_|\__,_| .__/ \___|_|  \__,_|___/|_| |_|
#                 |_|                             
#
# Script        : snapcrash
# Author        : Jens Ochmann
# Location      : /usr/local/bin/
# Description   : Terminates, updates, removes, and reinstalls the Snap Store to resolve common issues.
# Requires root : Yes

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo
echo -e "${YELLOW}Deleting all Snap Store processes...${NC}"
killall snap-store

if [ $? -eq 0 ]; then
    echo -e "${YELLOW}Snap Store processes successfully terminated.${NC}"
else
    echo -e "${RED}Error terminating Snap Store processes. They may not have been active.${NC}"
fi

echo
echo -e "${YELLOW}Updating Snaps...${NC}"
sudo snap refresh

echo
echo -e "${YELLOW}Updating package lists and performing a full upgrade...${NC}"
if sudo apt update && sudo apt full-upgrade -y; then
    echo -e "${YELLOW}System successfully updated.${NC}"
else
    echo -e "${RED}Error updating the system.${NC}"
fi

echo
echo -e "${YELLOW}Removing Snap Store...${NC}"
if sudo snap remove snap-store; then
    echo -e "${YELLOW}Snap Store successfully removed.${NC}"
else
    echo -e "${RED}Error removing the Snap Store.${NC}"
fi

echo
echo -e "${YELLOW}Installing Snap Store...${NC}"
if sudo snap install snap-store; then
    echo -e "${YELLOW}Snap Store successfully installed.${NC}"
else
    echo -e "${RED}Error installing the Snap Store.${NC}"
fi
