#!/bin/bash

#      _             _               
#  ___| |_ __ _ _ __| |_ _   _ _ __  
# / __| __/ _` | '__| __| | | | '_ \ 
# \__ \ || (_| | |  | |_| |_| | |_) |
# |___/\__\__,_|_|   \__|\__,_| .__/ 
#                             |_|  
#
# Script        : startup
# Author        : Jens Ochmann
# Location      : /usr/local/bin
# Description   : Install specified applications and run the 'dispatch' script to dispatch files from GitHub repository
# Requires root : Yes

# Colors
export NC='\033[0m' # No Color
export BLACK='\033[0;30m'
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export MAGENTA='\033[0;35m'
export CYAN='\033[0;36m'
export WHITE='\033[0;37m'

# Ensure root
root() {
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}This script must be run as root${NC}" >&2
   exit 1
fi
}

root

# Prompt the user to enter their username
read -p "${YELLOW}Please enter your username:${NC} " USERNAME

# Define HOME directory based on the entered username
HOME="/home/$USERNAME"

# Check if the entered username exists
if [ ! -d "$HOME" ]; then
    echo -e "${RED}Error: User '$USERNAME' does not exist or home directory not found.${NC}"
    exit 1
fi

# Check if the GitHub directory exists
GITHUB_DIR="$HOME/github"
if [ ! -d "$GITHUB_DIR" ]; then
    echo -e "${BLUE}$GITHUB_DIR ${YELLOW}does not exist.${NC}"
    echo -e "${YELLOW}Cloning repository from Github...${NC}"
	cd $HOME
	git clone https://github.com/ochi84/github.git
    echo -e "${YELLOW}Done.${NC}"
else
	echo -e "${YELLOW}Check for GitHub directory | ${GREEN}ok${NC}"
fi

# Install Dispatch
if sudo cp $HOME/github/dispatch /usr/local/bin/ && sudo chmod +x /usr/local/bin/dispatch; then
    echo -e "${YELLOW}'Dispatch' successfully installed and made executable.${NC}"
else
    echo -e "${RED}Failed to install and set execute permission on 'dispatch'.${NC}"
    exit 1
fi

echo -e "${YELLOW}Running 'dispatch'...${NC}"
    
# Ensure 'dispatch' is executable and available
if /usr/local/bin/dispatch; then
    echo -e "${YELLOW}'Dispatch' executed successfully.${NC}"
else
    echo -e "${RED}Failed to execute 'dispatch'.${NC}"
    exit 1
fi

# Load config file
CONFIG_FILE="$HOME/.config/sc.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "${RED}Error: Configuration file not found.${NC}"
    echo -e "${RED}Please ensure the configuration file 'sc.conf' exists at $HOME/.config/${NC}"
    exit 1
fi

echo -e "${YELLOW}Starting the installation of applications...${NC}"

# Function to install packages
install_packages() {
    local packages=("${@}")
    local installed=()
    for app in "${packages[@]}"; do
        if sudo apt install -y "$app"; then
            echo -e "${YELLOW}Installed $app successfully.${NC}"
            installed+=("$app")  # Add app to the list of successfully installed packages
        else
            echo -e "${RED}Failed to install $app. Check if the package exists or if there are network issues.${NC}"
        fi
    done
    echo -e "${YELLOW}Successfully installed the following packages:${NC}"
    printf '%s\n' "${installed[@]}"  # List successfully installed packages
}

# Display installation options with descriptions
echo -e "Select the installation type:"
echo -e "1 - Minimal Install: ${BLUE}Basic utilities like 'mc', 'vim', 'micro', 'ranger'.${NC}"
echo -e "2 - Minimal Plus Install: ${BLUE}Adds more advanced VIM plugins and tools on top of the Minimal Install.${NC}"
echo -e "3 - Expand Install: ${BLUE}Includes all packages from Minimal Plus and additional tools like 'git', 'fzf', 'exa'.${NC}"
echo -e "4 - Full Install: ${BLUE}The most comprehensive installation, including window managers and advanced applications.${NC}"
read -p "Enter your choice (1-4): " choice

# Prepare installation array based on user choice
all_packages=()
case $choice in
    1)
        all_packages+=("${minimal[@]}")
        ;;
    2)
        all_packages+=("${minimal[@]}")
        all_packages+=("${minimal_plus[@]}")
        ;;
    3)
        all_packages+=("${minimal[@]}")
        all_packages+=("${minimal_plus[@]}")
        all_packages+=("${expand[@]}")
        ;;
    4)
        all_packages+=("${minimal[@]}")
        all_packages+=("${minimal_plus[@]}")
        all_packages+=("${expand[@]}")
        all_packages+=("${full[@]}")
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

# Install selected packages
install_packages "${all_packages[@]}"

echo -e "${YELLOW}All desired applications have been installed.${NC}"
