#!/bin/bash

#                  _       _
#  _   _ _ __   __| | __ _| |_ ___ 
# | | | | '_ \ / _` |/ _` | __/ _ \
# | |_| | |_) | (_| | (_| | ||  __/
#  \__,_| .__/ \__,_|\__,_|\__\___|
#       |_|                    
#
# Script        : update
# Location      : /usr/local/bin
# Author        : Jens Ochmann
# Date          : 2024-05-18
# Description   : Performs updates and cleanup tasks on linux systems.
# Requires root : Yes

NC='\033[0m' # No Colo
RED='\033[0;31m'

# Ensure root
root() {
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}This script must be run as root${NC}" >&2
   exit 1
fi
}

root

# Ask for the username to update
echo
read -p "Enter the username to be updated: " USERNAME

# Define User-Dir (HOME)
USER_DIR="/home/$USERNAME"

# Load config file
CONFIG_FILE="$USER_DIR/.config/sc.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "${RED}Error: Configuration file not found.${NC}"
    echo -e "${RED}Please ensure the configuration file 'sc.conf' exists at $HOME/.config/${NC}"
    exit 1
fi

update_packages() {
    echo
    echo -e "${YELLOW}Updating all installed packages...${NC}"
    apt update && apt full-upgrade -y
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to update packages.${NC}" >&2
        return 1
    fi
}

cleanup_system() {
    echo
    echo -e "${YELLOW}Deleting temporary files...${NC}"
    rm -rf /tmp/* /var/tmp/*
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to delete temporary files.${NC}" >&2
        return 1
    fi

    echo
    echo -e "${YELLOW}Emptying the trash using trash-cli...${NC}"
    trash-empty
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to empty the trash.${NC}" >&2
        return 1
    fi

    echo
    echo -e "${YELLOW}Cleaning APT cache...${NC}"
    apt autoremove -y && apt autoclean
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to clean APT cache.${NC}" >&2
        return 1
    fi
}

# Start the maintenance process
echo
echo -e "${YELLOW}Starting system maintenance...${NC}"
update_packages
update_result=$?

cleanup_system
cleanup_result=$?

# if both update and cleanup were successful
if [ $update_result -eq 0 ] && [ $cleanup_result -eq 0 ]; then
    echo
    echo -e "${GREEN}System maintenance completed successfully!${NC}"
    echo
else
    echo
    echo -e "${RED}System maintenance encountered errors.${NC}" >&2
    echo
fi
