#!/bin/bash

#                  _       _       
#  _   _ _ __   __| | __ _| |_ ___ 
# | | | | '_ \ / _` |/ _` | __/ _ \
# | |_| | |_) | (_| | (_| | ||  __/
#  \__,_| .__/ \__,_|\__,_|\__\___|
#       |_|                    
#
# Script: System Maintenance
# Author: Jens Ochmann
# Description: Performs updates and cleanup tasks on Ubuntu 22.04 systems.
# Location: /usr/local/bin/system-maintenance
# Usage: Run as root to update packages and clean up the system.

# Ensure the script is run as root
if [ "$(id -u)" != "0" ]; then
   echo -e "\033[0;31mThis script must be run as root.\033[0m" 1>&2
   exit 1
fi

RED='\033[0;31m'  # Red for error messages
NC='\033[0m'      # No color

# Function to print errors in red
print_error() {
    echo -e "${RED}$1${NC}"
}

echo "Starting system update..."

# Update system packages
echo "Updating all installed packages..."
if ! apt update || ! apt full-upgrade -y; then
    print_error "Failed to update installed packages."
fi

echo "Starting system cleanup..."

# Delete temporary files
echo "Deleting temporary files..."
if ! rm -rf /tmp/* /var/tmp/*; then
    print_error "Failed to delete temporary files."
fi

# Empty the trash
echo "Emptying the trash..."
if ! rm -rf ~/.local/share/Trash/*; then
    print_error "Failed to empty the trash."
fi

# Clean up the apt cache
echo "Cleaning APT cache..."
if ! apt autoremove -y || ! apt autoclean; then
    print_error "Failed to clean APT cache."
fi

# Uncomment to enable old kernels removal
# echo "Removing old kernels..."
# if ! apt install byobu -y || ! purge-old-kernels; then
#     print_error "Failed to remove old kernels."
# fi

# Uncomment to enable journal logs cleanup
# echo "Cleaning up journal logs..."
# if ! journalctl --vacuum-time=2d; then
#     print_error "Failed to clean up journal logs."
# fi

echo "Update and cleanup completed!"
