#!/bin/bash

#                  _       _
#  _   _ _ __   __| | __ _| |_ ___ 
# | | | | '_ \ / _` |/ _` | __/ _ \
# | |_| | |_) | (_| | (_| | ||  __/
#  \__,_| .__/ \__,_|\__,_|\__\___|
#       |_|                    
#
# Script        : update
# Author        : Jens Ochmann
# Location      : /usr/local/bin
# Description   : Performs updates and cleanup tasks on linux systems.
# Requires root : Yes

# Define User-Dir (HOME)
USER_DIR="/home/jens"

# Load config file
CONFIG_FILE="$USER_DIR/.config/sc.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "${RED}Error: Configuration file not found.${NC}"
    echo -e "${RED}Please ensure the configuration file 'sc.conf' exists at $HOME/.config/${NC}"
    exit 1
fi

root # Ensure root (see sc.conf)

update_packages() {
    echo -e "${YELLOW}Updating all installed packages...${NC}"
    apt update && apt full-upgrade -y
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to update packages.${NC}" >&2
        return 1
    fi
}

cleanup_system() {
    echo -e "${YELLOW}Deleting temporary files...${NC}"
    rm -rf /tmp/* /var/tmp/*
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to delete temporary files.${NC}" >&2
        return 1
    fi

    echo -e "${YELLOW}Emptying the trash using trash-cli...${NC}"
    trash-empty
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to empty the trash.${NC}" >&2
        return 1
    fi

    echo -e "${YELLOW}Cleaning APT cache...${NC}"
    apt autoremove -y && apt autoclean
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to clean APT cache.${NC}" >&2
        return 1
    fi
}

# Start the maintenance process
echo -e "${YELLOW}Starting system maintenance...${NC}"
update_packages
update_result=$?

cleanup_system
cleanup_result=$?

# if both update and cleanup were successful
if [ $update_result -eq 0 ] && [ $cleanup_result -eq 0 ]; then
    echo -e "${GREEN}System maintenance completed successfully!${NC}"
else
    echo -e "${RED}System maintenance encountered errors.${NC}" >&2
fi
