name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thank you for creating this issue. I'll take care of this as soon as possible."
        pr-message: "Hi! Thank you for your pull request. I'll check it out as soon as possible."
